[tool.poetry]
name = "hilbert-plot"
version = "0.1.0"
description = ""
authors = ["BenG <j.j.goldberger@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.10.3"
plotly = "^6.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
